### ISSUE TITLE
2.0.4 not working after browser restart

### ISSUE THREAD

**Issue by RockinBandit** [autonome/Always-Right#13]
Needed to do a Firefox refresh today so Always Right was updated to 2.0.4 but it does not open to the next right it goes to the extreme right which has been up to 70 tabs away. Previous version worked seamlessly.

Using Firefox 54.0.1 32 bit

**Comment by autonome** [comment]
Thanks! Also reported in #7. If you disable and enable it, will work until
next restart. Working on finding cause and solution...

**Comment by autonome** [comment]
Fixed and pushed to AMO

**Comment by Nexion** [comment]
Unfortunately, the fix didn't solve the issue in my case. It only happens when opening a new blank tab (Ctrl-T or [+] button).
